export const ActionTypes = {
    GET_SATELLITE_LIST: "GET_SATELLITE_LIST",
    GET_SATELLITE_LIST_ERROR: "GET_SATELLITE_LIST_ERROR",
    CREATE_SATELLITE_EVENT_START: "CREATE_SATELLITE_EVENT_START",
    CREATE_SATELLITE_EVENT: "CREATE_SATELLITE_EVENT",
    CREATE_SATELLITE_EVENT_SUCCESS: "CREATE_SATELLITE_EVENT_SUCCESS",
    CREATE_SATELLITE_EVENT_FAILURE: "CREATE_SATELLITE_EVENT_FAILURE",
    SHOW_ALL_EVENTS: "SHOW_ALL_EVENTS",
    SHOW_ALL_EVENTS_FAILURE: "SHOW_ALL_EVENTS_FAILURE",
    SHOW_SELECTED_SATELLITE: "SHOW_SELECTED_SATELLITE",
    REMOVE_SELECTED_SATELLITE: "REMOVE_SELECTED_SATELLITE",
    SHOW_TLE_INFO: "SHOW_TLE_INFO",
    SHOW_TLE_INFO_FAILURE: "SHOW_TLE_INFO_FAILURE",
    SHOW_TLE_INFO_FROM_DB: "SHOW_TLE_INFO_FROM_DB"
};